-- Criar a tabela Pessoa primeiro (pois Usuario depende dela)
CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    cpf VARCHAR(14),
    data_nascimento DATE,
    email VARCHAR(255)
);

-- Criar a tabela Usuario
CREATE TABLE usuario (
    -- Campos da ChaveCompostaUsuario
    id BIGINT NOT NULL,
    rm VARCHAR(50) NOT NULL,
    
    senha VARCHAR(255),
    status VARCHAR(20), -- Mapeado como String pelo EnumType.STRING
    fk_pessoa BIGINT,
    
    -- Definição da Chave Primária Composta
    CONSTRAINT pk_usuario PRIMARY KEY (id, rm),
    
    -- Definição da Chave Estrangeira
    CONSTRAINT fk_usuario_pessoa FOREIGN KEY (fk_pessoa) REFERENCES pessoa(id)
);
