spring.application.name=projeto-usuarios

# Datasource MySQL
# Lembre-se de criar o banco 'meubanco' no seu MySQL antes de rodar
spring.datasource.url=jdbc:mysql://localhost:3306/meubanco?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=12356
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# 'update' altera o banco conforme suas entidades sem apagar os dados existentes
spring.jpa.hibernate.ddl-auto=create

# Logs de SQL (úteis para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

nano src/main/resources/application.properties
